### ISSUE TITLE
To Do list

### ISSUE THREAD

**Issue by earowang** [Tina-ye112/kiaora#1]
- [x] Style your code pls
- [x] Can't load the package with `load_all()`
- [x] Either use `lappy()` or `map()`, not in a mixed way
- [x] Add and document a data set `data/nzhousingprice`
- [x] Add `README.Rmd` & `README.md`

**Comment by earowang** [comment]
- [ ] Write a vignette on exploring NZ housing price

**Comment by earowang** [comment]
- [x] Pass `devtools::check()`

**Comment by earowang** [comment]
Also include the heatmap b/t bedrooms and bathrooms

**Comment by Tina-ye112** [comment]
OK
